# Generated by Django 5.0.6 on 2025-11-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
